import appleStock from './exercises/appleStock/appleStock';
import equalizeArr from './exercises/equalizeArr';
import jumpingClouds from './exercises/clouds';
import mostRepeated from './exercises/repeatedValue';
import result from './exercises/ticketOOP';
import longestNoRep from './exercises/longestNoRep';
import binarySearch from './exercises/binarySearch';
import getMaxSum from './exercises/maxSumContiguousSubArr';
import safePath from './exercises/safePath';
import getClock from './exercises/hourglass';
import getSmallestMissing from './exercises/smallestPositiveMissing';
import moveZeroesToEnd from './exercises/moveZerosToEnd';
import swapArray from './exercises/minimumSwaps';
import runningMedian from './exercises/runningMedian';

console.log(appleStock());
console.log(equalizeArr());
console.log(jumpingClouds());
console.log(mostRepeated());
console.log(result());
console.log(longestNoRep());
console.log(binarySearch());
console.log(getMaxSum());
console.log(safePath());
console.log(getClock());
console.log(getSmallestMissing());
console.log(moveZeroesToEnd());
console.log(swapArray());
console.log(runningMedian());
