import appleStock from './exercises/appleStock.js';
import equalizeArr from './exercises/equalizeArr.js';
import jumpingClouds from './exercises/clouds.js';
import mostRepeated from './exercises/repeatedValue.js';
import result from './exercises/ticketOOP.js';
import longestNoRep from './exercises/longestNoRep.js';
import binarySearch from './exercises/binarySearch.js';
import getMaxSum from './exercises/maxSumContiguousSubArr.js';
import safePath from './exercises/safePath.js';
import getClock from './exercises/hourglass.js';

console.log(appleStock());
console.log(equalizeArr());
console.log(jumpingClouds());
console.log(mostRepeated());
console.log(result());
console.log(longestNoRep());
console.log(binarySearch());
console.log(getMaxSum());
console.log(safePath());
console.log(getClock());
